// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaAPI.Helpers;

#nullable disable

namespace PruebaAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PruebaAPI.Entities.Pedido", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RestauranteID")
                        .HasColumnType("int");

                    b.Property<string>("cabecera")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("humedad")
                        .HasColumnType("int");

                    b.Property<int>("temperatura")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RestauranteID");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("PruebaAPI.Entities.Restaurante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nombreRestaurante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ubicacionRestaurante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("PruebaAPI.Entities.Pedido", b =>
                {
                    b.HasOne("PruebaAPI.Entities.Restaurante", "restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("restaurante");
                });
#pragma warning restore 612, 618
        }
    }
}
